### ISSUE TITLE
REANA spec file structure

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#10]
As mused about IRL, we may want to head towards something like the following REANA spec file structure:

```yml
version:
  reana:0.0.1
data:
  file: ./data/somefile.csv
  xrootd: root//someserver/somelocation/somefile.csv
code:
  file: code/myscript.py
  directory: mydirectory/
environment:
  type: docker
  image: python:2.7
workflow:
  type: yadage
  file: workflow.yml
output:
  file: foo.png
  directory: logs/
```

(to be called `reana.yml`? or `Reanafile`? or... ?)

**Comment by diegodelemos** [comment]
Based on the ongoing PR https://github.com/reanahub/reana-demo-root6-roofit/pull/2
```yaml
---
# version missing
metadata:
  author: "@reanahub/developers"
  title: "RooFit example"
# data label missing since there is no input for reana-demo-root6-roofit
code:
  files:
    - gendata.C
    - fitdata.C
env: # needs to be renamed to environment
  type: docker
  image: reanahub/reana-env-root6
workflow:
  type: yadage
  file: workflow.yml
parameters:
  events: 20000
output:
  files:
    - plot.png
```

- I see workflow parameters missing, but I don't have a strong opinion on whether it should be inside workflow tag or outside
- I would rename field `file` to `fields` under `code` and `data` and make it a list of elements so we can have more than one (since keys are unique we won't be able to have several files). Eventually it could be a list of complex objects such as:
```yaml
data:
  files:
    - location: ./data/somefile.csv
      description: 'Some description..'
      protocol: filesystem
    - localtion: ./data/someotherfile.csv
      description: 'Some other description ...'
      protocol: xrootd
```

**Comment by lukasheinrich** [comment]
I'm confuse what `code: ` and `environment` do.. in my mind it's the role of the workflow engine to decide the right environments to which it submits jobs into the job controller

```
version:
  reana:0.0.1
workflow:
  type: yadage
  file: workflow.yml
  default_environment: busybox
output:
  file: foo.png
  directory: logs/```

**Comment by tiborsimko** [comment]
The **code** is there for people who don't need to build container images.  They would use some, such as `root6-roofit`, and simply "mount" their code to be run within this environment. For advanced use cases, when people would build their images and the code would be inside already, then this property could be empty indeed.  (It's optional.)

The **environment** is useful to have outside of the workflow. Firstly, it is a very good point that the workflow should be able to specify its environment runtime demands. I imagine some workflow languages to dispatch some steps to this cloud, some other steps to that cloud, and doing the synthesis locally in the default environment. We would use the workflow language features for this, i.e. `workflow.yml` would *override* the default **environment** specification found in the REANA spec file, as it were.  (And, since we aim at a possibility to use different environments for different workflow steps, it wouldn't be enough to specify only one `default_environment` inside the **workflow** property anyway; we would need to go into each individual workflow step, which is best done reusing the workflow native language for that.) Secondly, we want to support different workflow languages, so it makes sense to specify some workflow parameters outside, if at all possible, say in case people want to try a different workflow runner for example.

BTW for some jobs it might be good to avoid using a formal workflow language altogether. If the workflow is basically a linear sequence of commands to run, one could reasonably use something like:

```yaml
version:
  - reana:0.0.1
metadata:
  - author: "John Doe"
  - title: "Very simple linear analysis"
  - date: "24 October 2017"
  - repository: https://github.com/johndoe/myanalysis
environment:
  - type: docker
  - image: python:2.7
code:
  - files:
    - ./code/myanalysis.py
inputs:
  - files:
    - ./data/mydata.csv
    - ./data/myconfig.py
  - parameters:
    - year_start: 1950
    - year_step: 2000
workflow:
  - type: shell
  - commands:
    - echo whoami
    - python /code/myanalysis.py --config /inputs/myconfig.py --start=${YEAR_START} 
--stop=${YEAR_STOP}
    - ls /outputs/plot.png
    - echo done
outputs:
  - files
    - plot.png
```

(A hypothetical example on how to make the REANA adoption even simpler by abstracting away the formal workflow definition part. This could work for very simple container reuse scenarios, when the steps to run are linear and simple, and when the container producer is not the same person as the container user. The Note the resemblance to Travis, GitLab CI style of running things.)
