### ISSUE TITLE
reana.yaml: optional parameters and other sections

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#109]
When a workflow does not need any parameters, one has to still provide in ``reana.yaml`` something in the `parameters` section, like:

```yaml
inputs:
  files:
   - generate.C
   - plot.C
  parameters:
    none: none
```

If one leaves `parameters` out, there will be a traceback.

It would be great if almost all sections are optional to improve UX in cases like these.

E.g. `environments` can be optional too, since the container images may be specified in the workflow engine specs e.g. in case of yadage.
