### ISSUE TITLE
reana spec: make environment and code optional

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#124]
The `environment` and `code` keys in the reana spec can be superfluous, since the workflow engine specifies a lot of the environment and code. E.g. for the recast example, the spec could look like

```
version: 0.X.0
inputs:
  parameters:
    did: 404958
    xsec_in_pb: 0.00122
    dxaod_file: http://physics.nyu.edu/~lh1132/capdemo/mc15_13TeV.123456.cap_recast_demo_signal_one.root
outputs:
  files:
    - outputs/statanalysis/fitresults/pre.png
workflow:
  type: yadage
  file: workflow.yml
  options:
    toplevel: workflow
```
