### ISSUE TITLE
inputs: directory support

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#171]
Currently we support `files` and `parameters`:

```yaml
version: 0.3.0
inputs:
  files:
    - code/worldpopulation.ipynb
    - data/World_historical_and_predicted_populations_in_percentage.csv
  parameters:
    region: Africa
    year_min: 1500
    year_max: 2012
```

When an analysis contains hundreds of files, it won't be practical to list them all in `reana.yaml` in this way.  

Let us support the concept of `directories` in addition to `files` so that one could have:

```yaml
version: 0.3.0
inputs:
  directories:
    - code
    - data
  files:
    - paper/figures/fig1.gnuplot
  parameters:
    region: Africa
    year_min: 1500
    year_max: 2012
```

Alternatively, we could use a syntax like `mydirectory/**` to express the notion of including all the files recursively under the given directory:

```yaml
inputs:
  files:
    - code/**
    - data/**
```

Short and sweet?
