### ISSUE TITLE
cli: download wrapper command

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#173]
As a mirror to #172, let us provide a wrapper CLI command to download all the output files that are listed in `reana.yaml`.

Consider having:

```yaml
outputs:
  files:
   - results/plot1.png
   - results/plot3.png
```

and doing:

```console
$ reana-client download --all
```

or even shortly:

```console
$ reana-client download 
```

This should automatically download `plot1.png` and `plot3.png` but nothing else.
