### ISSUE TITLE
yadage: make toplevel configurable

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#356]
yadage load has a configurable kwarg `toplevel` but currently I don't see any way to configure this from `reana.yml`. From the code it seems like this could be easy to add?

https://github.com/reanahub/reana-client/blob/fa025d0e57fbdde5c9ff86595e3c991cb2a2483e/reana_client/utils.py#L40

**Comment by tiborsimko** [comment]
Do you have a nice example analysis using different toplevel? Would `toplevel` be part of Yadage workflow YAML specs, or would it only be used as "operational option"  in the `yadage-run --toplevel ...` command?

**Comment by lukasheinrich** [comment]
being able to specify `toplevel` allow e.g. using remote workflows

```
yadage-run workdir madgraph_delphes.yml -p nevents=100 --toplevel from-github/phenochain
```

i'd have something like this in reana.yml


```
workflow:
  type: yadage
  file: workflow.yml
  toplevel: workflow
```

```
workflow:
  type: yadage
  file: madgraph_delphes.yml
  toplevel: from-github/phenochain
```
