### ISSUE TITLE
reana-client doesn't warn about missing keytab when using htcondorcern backend

### ISSUE THREAD

**Issue by clelange** [reanahub/reana-client#381]
Example config:

```yaml
version: 0.6.0
workflow:
  type: serial
  resources:
    cvmfs:
      - cms.cern.ch
  specification:
    steps:
      - name: testing
        environment: gitlab-registry.cern.ch/awesome-workshop/payload-docker-cms:0950e980
        compute_backend: htcondorcern
        commands:
          - ls
```

A job submission to HTCondor only works with a keytab present. Could/Should catch already at submission/validation time.
