### ISSUE TITLE
reana.yaml: add support for outputs.directories

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#536]
In #402 a support was added for downloading directories.

However the feature was not fully represented in `reana.yaml` syntax for the "outputs" clause.

Currently, users would have to write:

```yaml
outputs:
  files:
    - plots
```

which will work as expected (i.e. "plots" is recognised as a directory and a zip tarball will be sent for download).

What we should do is to allow:

```yaml
outputs:
  directories:
    - plots
```

which would be more consistent with the syntax of the "inputs" clause:

```yaml
inputs:
  parameters:
    did: 404958
    xsec_in_pb: 0.00122
    dxaod_file: https://recastwww.web.cern.ch/recastwww/data/reana-recast-demo/mc15_13TeV.123456.cap_recast_demo_signal_one.root
  directories:
    - workflow
```

What we should do:

- implement support for "directories" in "outputs" clause;
- make sure things are working well if users specify multiple "files" and "directories" in the "outputs" clause;
- enrich the documentation accordingly.

Notes: Concerning the multiple outputs item above, currently the tarball is named like `download_2021-07-09-114314.zip`.  This would make it fuzzy which directories are downloaded in case users ask for more, such as:

```yaml
outputs:
  directories:
    - plots
    - histograms
```

We may want to name the tarballs starting from the desired directory name.  (perhaps even including things like workflow name and run number?)
