### ISSUE TITLE
snakemake: parameters validation

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-client#543]
**Current behavior**

Currently we support parameter validation on the client-side via `reana-client validate`. To get more familiar with this feature read [this blog post section](https://blog.reana.io/posts/2021/reana-0.7.3/#validating-workflow-parameters), where the purpose of it is very well explained with some practical examples.

This feature is supported in Serial, Yadage and CWL workflows.

**Expected behavior**

The user should be able to run the very same command with Snakemake workflows, e.g. `reana-client validate -f reana-snakemake.yaml`

All the parameter validation logic resides in this [module](https://github.com/reanahub/reana-client/blob/master/reana_client/validation/parameters.py), where each workflow engine has a class (`SerialParameterValidator`, `YadageParameterValidator` ...)

The main goal of each of these classes is basically parsing the workflow specification to grab the parameters declared both in the reana.yaml spec and in the Snakefile to compare them and display the appropriate warnings if needed. We need to implement a `SnakemakeParameterValidator` class with at least a `validate_environment` method that parses/loads the Snakefile and grabs the parameters.

The logic to parse and load the snakemake specification (Snakefile) should come from https://github.com/reanahub/reana-client/issues/540. After this, one should be able to access the multiple rules and values declared in the Snakefile.

**Expected output**

`reana-snakemake.yaml`:
```yaml
version: 0.8.0
inputs:
  files:
    - code/helloworld.py
    - data/names.txt
  directories:
    - workflow/snakemake
  parameters:
    input: workflow/snakemake/inputs.yaml
    foo: 'foo'
workflow:
  type: snakemake
  file: workflow/snakemake/Snakefile
outputs:
  files:
  - results/greetings.txt
```

`workflow/snakemake/Snakefile`:
```make
rule all:
    input:
        "results/greetings.txt"

rule helloworld:
    input:
        helloworld=config["helloworld"],
        inputfile=config["inputfile"],
    params:
        sleeptime=config["sleeptime"]
        bar="bar"
...
```

Output:
```console
$ reana-client validate -f reana-snakemake.yaml
==> Verifying REANA specification file... ~/code/reanahub/reana-demo-helloworld/reana-snakemake.yaml
  -> SUCCESS: Valid REANA specification file.
==> Verifying REANA specification parameters...
  -> WARNING: REANA input parameter "foo" does not seem to be used.
==> Verifying workflow parameters and commands...
  -> WARNING: Snakemake parameter "bar" found on step "helloworld" is not defined in input parameters.
```
